### ISSUE TITLE
Codecs

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageProcessor#446]
This issue serves to collect various issues with the image codecs. Additional issues will be added upon identification.

Png
- [ ] Decoder doesn't decode progressive files #379 
- [ ]  Encoder does not encode progressive files

Jpeg
- [x] Decoder does not decode CMYK files #444 
- [ ] Encoder does not encode CMYK files
- [ ] Encoder does not encode progressive files

Tiff
- [ ] No Tiff support #464

**Comment by JimBobSquarePants** [comment]
This issue was moved to JimBobSquarePants/ImageSharp#10
